# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10511d3ac2fa09961c824e5058f8b89ac734bda02c680d026c167283abd2de2d7483a08b691b776098c05bfb4d1136efa70b9a034bfee95567d9153ec3db06f4

test:
  secret_key_base: 1a55b4cafebde332cd1d0adf88efa4d423fa094df85bf1bc5ea4278a87cc1d16797776c9a78b253521e391718f929e6f63bd6fc4c6a21275d3a11e13bc5f8917

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
